version: "3"

services:

  events-redis:
    container_name: events-redis
    image: redislabs/redismod:latest
    restart: unless-stopped
    volumes:
      - ./volume/redis/redis_data:/data
      - ./volume/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - container=docker
    logging:
      driver: "json-file"

  sails_events:
    container_name: sails_events
    image: ghcr.io/kpturner/sails_events:${INSTANCE}-latest
    restart: unless-stopped
    volumes:
      - ./volume/logs:/usr/src/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - container=docker
      - REDIS_HOST=events-redis
      - DB_HOST=host.docker.internal
      - BLUEBIRD_W_FORGOTTEN_RETURN=0
    ports:
      - "${EVENTS_PORT}:1337"
