cd /usr/sails/projects/events
bash gitupdate.sh
cd /usr/sails/projects/eventstest
bash gitupdate.sh
cd /usr/sails/projects/surrey
bash gitupdate.sh
cd /usr/sails/projects/mtsfc
bash gitupdate.sh
cd /usr/sails/projects/pgsl
bash gitupdate.sh