name: Publish docker images - Hamtun

on:

  # Run if a PR is closed (and has been merged) or on workflow_dispatch
  pull_request:
    branches:
      - main
    types: [closed]

  workflow_dispatch:

jobs:

  build-and-push:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Create config file and restart cmd from secret for Hamtun
        run: |
          mkdir -p secrets
          echo "${{ secrets.HAMTUN_CONFIG }}" > secrets/secrets_hamtun.json

      - name: Build and push with "latest" for Hamtun
        uses: ./.github/workflows/composites/docker-build-push-version
        with:
          version: hamtun-latest
          username-github: ${{ github.actor }}
          password-github: ${{ secrets.REPO_ACCESS_TOKEN }}
          repo: 'kpturner/sails_events'
          config: 'secrets/secrets_hamtun.json'
          assets: 'hamtun'
          ecr-uri: 'ghcr.io'
