name: Delete old container images

on:
  schedule:
    - cron: '0 0 * * *' # Midnight
  workflow_dispatch:

jobs:
  clean-ghcr-prod:
    name: Delete old unused prod container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v1
        with:
          image-names: 'sails_events'
          cut-off: One minute ago UTC
          keep-at-least: 0
          filter-tags: 'sha-*,pgl-latest'
          account-type: personal
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

    clean-ghcr-test:
      name: Delete old unused test container images
      runs-on: ubuntu-latest
      steps:
        - name: Delete old images
          uses: snok/container-retention-policy@v1
          with:
            image-names: 'sails_events'
            cut-off: One month ago UTC
            keep-at-least: 1
            filter-tags: 'sha-*,pgl-test-latest'
            account-type: personal
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
